CREATE TABLE users(
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(30) NOT NULL,
	phone_number VARCHAR(20) UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)